# Generated by Django 3.1.1 on 2022-12-27 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('empid', models.CharField(help_text='Employee ID', max_length=4, primary_key=True, serialize=False)),
                ('ename', models.CharField(max_length=50)),
                ('degree', models.CharField(max_length=30)),
                ('post', models.CharField(max_length=20)),
                ('salary', models.IntegerField()),
            ],
        ),
    ]
